[theme]
primaryColor="#ff4b4b"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#ffffff"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
